### ISSUE TITLE
[Forum] CSS improvements

### ISSUE THREAD

**Issue by ximex** [Admidio/website#17]
```css
blockquote {
    background-color: #fff;
    border-color: #ebebeb;
    font-size: 14px; /* Add */
}
blockquote::before {
    content: '\201C';
    position: absolute;
    font-family: 'Trebuchet MS';
    top: 9px; /* Change */
    right: 18px; /* Change */
    height: 16px;
    font-size: 30px;
    line-height: 30px;
    opacity: .5;
    pointer-events: none;
}

body {
    font-family: Titillium, sans-serif;
    letter-spacing: 0.05em; /* Remove it here and add it to specific elements => fixes styles in navbar etc */
}

/* New */
.navbar {
    min-height: none;
}
```
