### ISSUE TITLE
[Forum] CSS improvements the 2nd

### ISSUE THREAD

**Issue by ximex** [Admidio/website#18]
```css
fieldset.quick-login input.inputbox {
    width: 15%; /* remove */
    vertical-align: middle;
    margin-right: 5px;
}

/* remove */
.button {
    height: auto !important;
}

/* remove */
.nav-link {
    width: 25px !important;
}

.navbar {
    min-height: 0; /* change */
}
```
